#!/bin/bash
set -e

usage() {
  test "$1" && echo -e Error: $1\\n || echo -n
  cat <<EOF
  Usage: $(basename $0) <NIX-FILE>
EOF
  exit 1
}

# Default values
config="default.nix"

# Parse CLI arguments
while test $1;do
  case $1 in
    -d|--debug) debug=1;set -x;shift;;
    -*) usage;;
    *) config="$1";shift;;
  esac
done

eval-env() {
  nix-instantiate 2>&- --eval \
    -E "let env = import \"$(realpath "$config")\" {}; in toString ($1)" \
  | sed 's/^"//;s/"$//'
}
build-env() {
  nix-build --no-out-link \
    -E "let env = import \"$(realpath "$config")\" {}; in ($1)"
}

initRepo=$(build-env env.emptyRepo)
output=$(eval-env env.infoFile)
settings=$(build-env env.settings)
build_inputs=$(eval-env '(import <nixpkgs> {}).lib.makeBinPath env.config.buildInputs')
extra_deps=$(sed 's/^\[//;s/\]$//;s/\(.\)$/\1,/' \
  $(build-env '(import <nixpkgs> {}).writeText "extra-deps.json" (builtins.toJSON env.deps)'))

TMP_REPO="$(mktemp -d --tmpdir mavenix-m2-repo.XXXXXX)"
cleanup() {
  rm -rf "$TMP_REPO" || echo -n
}
trap "trap - TERM; cleanup; kill -- $$" EXIT INT TERM

cp -rf $initRepo/* $TMP_REPO >/dev/null 2>&1 || true
chmod -R +w "$TMP_REPO" || echo >&2 Failed to set chmod on temp repo dir.

mvn_flags="$(test "$debug" && printf %s "-e -X" || true)"
mvn_() { mvn $mvn_flags -B -nsu --settings "$settings" "$@"; }
mvn_out() { mvn -B -nsu --settings "$settings" "$@"; }

echo >&2 "ADDING BUILD INPUTS TO \$PATH"
export PATH="$build_inputs:$PATH"

echo >&2 "RUNNING MAVEN PACKAGE"
mvn_ >&2 package -Dmaven.test.skip.exec=true -DskipTests -Dmaven.repo.local=${TMP_REPO}

echo >&2 "GETTING PROJECT INFO"
pom="$(mvn_out help:effective-pom | grep -v '^\[\|^Effective \|^$' | xq -c .)"
projects="$(jq -c '.projects.project // [.project]' <<<"$pom")"
pq() { jq -rc "$1" <<<"$projects"; }
export -f pq

groupId="$(pq .[0].groupId)"
artifactId="$(pq .[0].artifactId)"
version="$(pq .[0].version)"

modules="$(pq '[.[] | {name: (.artifactId + "-" + .version), groupId, artifactId, version, path: (.build.directory | sub("^'$PWD'/"; "./") | sub("/target"; ""))}]')"

echo >&2 "RESOLVING MAVEN DEPENDENCIES"
mvn_ >&2 dependency:go-offline -Dmaven.repo.local=${TMP_REPO}

echo >&2 "CREATING OUTPUT"
(
echo -n "{
  \"name\": \"$artifactId-$version\",
  \"groupId\": \"$groupId\",
  \"artifactId\": \"$artifactId\",
  \"version\": \"$version\",
  \"submodules\": $modules,
  \"deps\": [ $extra_deps"
( cd $TMP_REPO
remotes="$(find . -type f -name "*.repositories" | sed 's|^\./||' | sort)"
sep=""
for remote in $remotes; do
  dir="$(dirname "$remote")"
  files="$(find "$dir" -type f ! -name "*.repositories" ! -name "*.sha1" \
    | grep -v '^#' "$remote" | sed "s|^|$dir/|")"
  for file_ in $files; do
    file=$(echo $file_ | cut -d '>' -f1)
    # Maven 3.0.5 for 3.3.9 use $file instead of $file_real
    file_real=$(echo $(echo $file | sed 's/-SNAPSHOT\./-[0-9]*\./'))
    repo=$(echo $file_ | cut -d '>' -f2 | sed 's/=$//')
    test "$repo" || continue
    echo -n "$sep
    {\"path\":\"$file_real\",\"sha1\":\"$(grep -Eo '[0-9a-zA-Z]{40}' < $file_real.sha1)\"}"
    sep=","
  done
done

echo -n "
  ],
  \"metas\": ["
metafiles="$(find . -type f -name "maven-metadata-*.xml"  | sed 's|^\./||' | sort)"
sep=""
for file in $metafiles; do
  repo=$(basename $file | sed 's/^maven-metadata-//;s/\.xml$//')
  [[ "$repo" && "$repo" != "local"  ]] || continue
  echo -n "$sep{
      \"path\": \"$(dirname $file)\",
      \"content\": \"$(sed ':a;N;$!ba;s/\n/\\n/g;s/\"/\\\"/g' $file)\"
    }"
  sep=", "
done
)
echo -n "
  ]
}
"
) > "$output"
